name: flutter_tdd
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  faker: ^2.2.0
  http: ^1.4.0
  getwidget: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  flutter_lints: ^5.0.0
  test: ^1.25.15
  build_runner: ^2.5.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  image_path_android: assets/icon/ios.png
  ios: true
  image_path_ios: assets/icon/ios.png
  adaptive_icon_background: assets/icon/background.png
  adaptive_icon_foreground: assets/icon/foreground.png
  min_sdk_android: 21
